### ISSUE TITLE
No module named 'MolKit'

### ISSUE THREAD

**Issue by xxrelax** [EDAPINENUT/CBGBench#6]
你好，感谢你出色的工作。
我在进行分子评估时需要问题No module named 'MolKit'，请问我该在哪儿下载这个包。

**Comment by EDAPINENUT** [comment]
能否更具体一点 比如在哪个文件的哪里出现的错误。 由于代码框架庞大，目前不止我一个人在运营，我很难定位到bug的位置

**Comment by xxrelax** [comment]
Exception has occurred: ModuleNotFoundError
No module named 'MolKit'
..../AutoDockTools_py3/AutoDockTools/Utilities24/prepare_receptor4.py", line 18, in <module>
    from MolKit import Read
ModuleNotFoundError: No module named 'MolKit'

**Comment by EDAPINENUT** [comment]
•	MolKit 可能是某些分子模拟工具（如 AutoDockTools）的依赖，建议查看这些工具的安装指南或安装整个工具包来解决依赖问题。
看起来是安装autodock vina时遇到了问题。我们在安装vina时并没有出现过类似的问题。
可以参照autodock vina的官方文档https://autodock-vina.readthedocs.io/en/latest/docking_flexible.html进行安装，其他相关安装技术问题，可以直接至autodock vina的github中询问。
我们没办法对第三方软件版本与系统的适配性进行解决。
