### ISSUE TITLE
How can I use D3FG to generate molecules based on my own protein binding pocket?

### ISSUE THREAD

**Issue by Bruce410526** [EDAPINENUT/CBGBench#7]
Thank you for open-sourcing your work; I have learned a lot from it. I currently have my own protein-ligand structure and would like to use D3FG to generate molecules. Could you please guide me on how to process the raw structure files to create the input files required by the model, and ultimately generate molecules within the binding pocket of my protein?

**Comment by EDAPINENUT** [comment]
We sincerely apologize that our code does not currently support this functionality. However, you can prepare your own protein-ligand pairs in `file_name.pkl` format and use `./scripts/extract_pockets.py` to prepare the pockets. Afterward, you can modify the dataset parsing in sample.py following the same logic. In fact, this is exactly how we handled the process in the case study section.
