### ISSUE TITLE
Where and when could you provide pretrained pt models?

### ISSUE THREAD

**Issue by jiminbot20** [EDAPINENUT/CBGBench#8]
2. Also, you can use our pretrained ones from Google Drives [TODO: Release the pretrained models], the corresponding pretrained data file names to different tasks and models are provided in the table below:
TODO: Table with pretrained models

Download the pretrained .pt checkpoints that you need, and copy them into ./logs/, which will lead to the following directory structure:

**As you wrote above Readme, Where and when could you provide pretrained pt models?**

**Comment by EDAPINENUT** [comment]
Thanks for your following.
The paper has just been submitted, and after it has been published, we will release all the pretrained ones.

**Comment by EDAPINENUT** [comment]
We have tested some of the retrained models and uploaded them to the Google Drive. You can now download them and for further usage.
